[project]
name = "comet"
version = "0.1.0"
description = "Stremio's fastest torrent/debrid search add-on."
authors = [
    { name = "Goldy", email = "153996346+g0ldyy@users.noreply.github.com" }
]
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.11.12",
    "aiosqlite>=0.21.0",
    "asyncio>=3.4.3",
    "asyncpg>=0.30.0",
    "bencode-py>=4.0.0",
    "curl-cffi>=0.9.0",
    "databases>=0.9.0",
    "demagnetize>=0.3.0",
    "fastapi>=0.115.6",
    "jinja2>=3.1.5",
    "loguru>=0.7.3",
    "mediaflow-proxy>=1.9.7",
    "orjson>=3.10.15",
    "pydantic-settings>=2.7.1",
    "rank-torrent-name>=1.6.0",
    "uvicorn>=0.32.1",
]
